// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../development/js_dev/googkit_index.js', ['googkit_index'], ['foo.Example'], false);
goog.addDependency('../../../../development/js_dev/main.js', ['main'], ['piine.App'], false);
goog.addDependency('../../../../development/js_dev/piine/app.js', ['piine.App'], ['goog.events.EventHandler', 'goog.events.EventTarget', 'goog.events.EventType', 'piine.View', 'socketio.Socket'], false);
goog.addDependency('../../../../development/js_dev/piine/fx/dom/textshadowanimation.js', ['piine.fx.dom.TextShadowAnimation'], ['goog.array', 'goog.fx.dom.PredefinedEffect'], false);
goog.addDependency('../../../../development/js_dev/piine/view.js', ['piine.View'], ['goog.color', 'goog.dom', 'goog.dom.classes', 'goog.events.EventHandler', 'goog.fx.AnimationParallelQueue', 'goog.fx.dom.BgColorTransform', 'goog.fx.dom.ColorTransform', 'goog.style', 'goog.ui.Component', 'piine.fx.dom.TextShadowAnimation'], false);
goog.addDependency('../../../../development/js_dev/socketio/socket.js', ['socketio.Socket'], ['goog.Uri', 'goog.array', 'goog.asserts', 'goog.dom', 'goog.events.EventHandler', 'goog.events.EventTarget'], false);
