// This file was autogenerated by closure/library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../development/js_dev/main.js', ['main'], ['piine.App']);
goog.addDependency('../../../../development/js_dev/piine/app.js', ['piine.App'], ['goog.events.EventHandler', 'goog.events.EventTarget', 'goog.events.EventType', 'piine.View', 'socketio.Socket']);
goog.addDependency('../../../../development/js_dev/piine/fx/dom/textshadowanimation.js', ['piine.fx.dom.TextShadowAnimation'], ['goog.array', 'goog.fx.dom.PredefinedEffect']);
goog.addDependency('../../../../development/js_dev/piine/view.js', ['piine.View'], ['goog.color', 'goog.dom', 'goog.dom.classes', 'goog.events.EventHandler', 'goog.fx.AnimationParallelQueue', 'goog.fx.dom.BgColorTransform', 'goog.fx.dom.ColorTransform', 'goog.style', 'goog.ui.Component', 'piine.fx.dom.TextShadowAnimation']);
goog.addDependency('../../../../development/js_dev/socketio/socket.js', ['socketio.Socket'], ['goog.Uri', 'goog.array', 'goog.asserts', 'goog.dom', 'goog.events.EventHandler', 'goog.events.EventTarget']);
