// This file was autogenerated by closure/library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../development/js_dev/main.js', ['main'], ['piine.App']);
goog.addDependency('../../../../development/js_dev/piine/app.js', ['piine.App'], ['goog.events.EventHandler', 'goog.events.EventTarget', 'goog.events.EventType', 'piine.View', 'socketio.Socket']);
goog.addDependency('../../../../development/js_dev/piine/graph/fx/effect.js', ['piine.graph.fx.Effect'], ['goog.Disposable']);
goog.addDependency('../../../../development/js_dev/piine/graph/fx/reactioneffect.js', ['piine.graph.fx.ReactionEffect'], ['piine.graph.fx.Effect']);
goog.addDependency('../../../../development/js_dev/piine/graph/math/math.js', ['piine.graph.math'], ['goog.math']);
goog.addDependency('../../../../development/js_dev/piine/graph/userreactiongraph.js', ['piine.graph.UserReactionGraph'], ['goog.Disposable', 'goog.Timer', 'goog.array', 'goog.math', 'goog.structs', 'goog.structs.Map', 'goog.structs.Set', 'goog.ui.Component', 'piine.graph.fx.ReactionEffect', 'piine.graph.math']);
goog.addDependency('../../../../development/js_dev/piine/view.js', ['piine.View'], ['goog.color', 'goog.dom', 'goog.ui.Component', 'piine.graph.UserReactionGraph']);
goog.addDependency('../../../../development/js_dev/socketio/socket.js', ['socketio.Socket'], ['goog.Uri', 'goog.array', 'goog.asserts', 'goog.dom', 'goog.events.EventHandler', 'goog.events.EventTarget']);
