// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../development/js_dev/googkit_index.js', ['googkit_index'], ['foo.Example'], false);
goog.addDependency('../../../../development/js_dev/main.js', ['main'], ['piine.App'], false);
goog.addDependency('../../../../development/js_dev/piine/app.js', ['piine.App'], ['goog.events.EventHandler', 'goog.events.EventTarget', 'goog.events.EventType', 'piine.View', 'socketio.Socket'], false);
goog.addDependency('../../../../development/js_dev/piine/graph/fx/effect.js', ['piine.graph.fx.Effect'], ['goog.Disposable'], false);
goog.addDependency('../../../../development/js_dev/piine/graph/fx/reactioneffect.js', ['piine.graph.fx.ReactionEffect'], ['piine.graph.fx.Effect'], false);
goog.addDependency('../../../../development/js_dev/piine/graph/math/math.js', ['piine.graph.math'], ['goog.asserts', 'goog.math'], false);
goog.addDependency('../../../../development/js_dev/piine/graph/userreactiongraph.js', ['piine.graph.UserReactionGraph'], ['goog.Disposable', 'goog.Timer', 'goog.array', 'goog.asserts', 'goog.math', 'goog.structs', 'goog.structs.Map', 'goog.structs.Set', 'goog.ui.Component', 'piine.graph.fx.ReactionEffect', 'piine.graph.math'], false);
goog.addDependency('../../../../development/js_dev/piine/view.js', ['piine.View'], ['goog.color', 'goog.dom', 'goog.ui.Component', 'piine.graph.UserReactionGraph'], false);
goog.addDependency('../../../../development/js_dev/socketio/socket.js', ['socketio.Socket'], ['goog.Uri', 'goog.array', 'goog.asserts', 'goog.dom', 'goog.events.EventHandler', 'goog.events.EventTarget'], false);
