// This file was autogenerated by closure/library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../development/js_dev/main.js', ['main'], ['piine.App']);
goog.addDependency('../../../../development/js_dev/piine/app.js', ['piine.App'], ['goog.events.EventHandler', 'goog.events.EventTarget', 'goog.events.EventType', 'goog.net.WebSocket', 'piine.View']);
goog.addDependency('../../../../development/js_dev/piine/view.js', ['piine.View'], ['goog.dom', 'goog.dom.classes', 'goog.fx.AnimationParallelQueue', 'goog.fx.dom.BgColorTransform', 'goog.style', 'goog.ui.Component']);
